### ISSUE TITLE
Admin provision doesn't complete

### ISSUE THREAD

**Issue by gemerick** [biemond/biemond-orawls-vagrant-12.2.1#1]
The only changes made were the software folder and jdk version.

Virtualbox 5.0.10
Vagrant 1.7.4
Puppet v4.2.1
jdk1.8.0_71

Jdk was installed. 
Node managers are running.
Console is running on 7101.

It seems to timeout on the t3s connection.

Any help appreciated.

Log snippet:
==> admin: Notice: /Stage[main]/Userconfig/Orawls::Storeuserconfig[Wls12c]/Exec[execwlst Wls12cstoreUserConfig.py]/returns: Connecting to t3://10.10.10.10:7101 with userid weblogic ...
==> admin: Notice: /Stage[main]/Userconfig/Orawls::Storeuserconfig[Wls12c]/Exec[execwlst Wls12cstoreUserConfig.py]/returns: Successfully connected to Admin Server "AdminServer" that belongs to domain "plain_Wls".
==> admin: Notice: /Stage[main]/Userconfig/Orawls::Storeuserconfig[Wls12c]/Exec[execwlst Wls12cstoreUserConfig.py]/returns: 
==> admin: Notice: /Stage[main]/Userconfig/Orawls::Storeuserconfig[Wls12c]/Exec[execwlst Wls12cstoreUserConfig.py]/returns: Warning: An insecure protocol was used to connect to the server. 
==> admin: Notice: /Stage[main]/Userconfig/Orawls::Storeuserconfig[Wls12c]/Exec[execwlst Wls12cstoreUserConfig.py]/returns: To ensure on-the-wire security, the SSL port or Admin port should be used instead.
==> admin: Notice: /Stage[main]/Userconfig/Orawls::Storeuserconfig[Wls12c]/Exec[execwlst Wls12cstoreUserConfig.py]/returns: 
==> admin: Notice: /Stage[main]/Userconfig/Orawls::Storeuserconfig[Wls12c]/Exec[execwlst Wls12cstoreUserConfig.py]/returns: Creating the key file can reduce the security of your system if it is not kept in a secured location after it is created. Creating new key...
==> admin: Notice: /Stage[main]/Userconfig/Orawls::Storeuserconfig[Wls12c]/Exec[execwlst Wls12cstoreUserConfig.py]/returns: The username and password that were used for this WebLogic Server connection are stored in /home/oracle/oracle-plain_Wls-WebLogicConfig.properties and /home/oracle/oracle-plain_Wls-WebLogicKey.properties.
==> admin: Notice: /Stage[main]/Userconfig/Orawls::Storeuserconfig[Wls12c]/Exec[execwlst Wls12cstoreUserConfig.py]/returns: executed successfully
==> admin: Info: index wls_user 
==> admin: Info: Executing: wlstScript with action index
==> admin: Info: domain found default
==> admin: Info: Starting the wls daemon for domain default
==> admin: Info: Connecting to wls on url t3s://10.10.10.10:7002
==> admin: Info: Executing wls-script /tmp/wlstScript20160120-6197-1pxmdyy.py with timeout = 120
==> admin: Info: Connecting to wls on url t3s://10.10.10.10:7002
==> admin: Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
==> admin: Error: Failed to apply catalog: timeout on reading expected output from daemon process.
==> admin: /tmp/vagrant-puppet/environments/development/modules/easy_type/lib/easy_type/daemon.rb:77:in `rescue in timed_readline'
==> admin: /tmp/vagrant-puppet/environments/development/modules/easy_type/lib/easy_type/daemon.rb:73:in`timed_readline'
==> admin: /tmp/vagrant-puppet/environments/development/modules/easy_type/lib/easy_type/daemon.rb:62:in `sync'
==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/utils/wls_daemon.rb:50:in`execute_script'
==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/utils/wls_access.rb:347:in `execute_wlst'
==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/utils/wls_access.rb:174:in`block in wlst'
==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/utils/wls_access.rb:172:in `each'
==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/utils/wls_access.rb:172:in`wlst'
==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/puppet/type/wls_user.rb:19:in `block (2 levels) in module:Puppet'

**Comment by biemond** [comment]
strange it is working for me.

Did you get the latest version because I was using this box as a test box.

**Comment by biemond** [comment]
I updated some config and latest version of orawls

**Comment by biemond** [comment]
Thanks a lot for reporting this,

I found some serious bugs.

**Comment by gemerick** [comment]
You're welcome, appreciate this project. It looks very promising.

I tried commit 623411d late yesterday and had the same issue. 

I just updated to commit e283d5b. It failed in the same spot, however the error messages are a bit different. I've included what I think is important. If I can send anything else to help, please let me know.

==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/utils/wls_access.rb:347:in `execute_wlst'
==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/utils/wls_access.rb:174:in`block in wlst'
==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/utils/wls_access.rb:172:in `each'
==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/utils/wls_access.rb:172:in`wlst'
==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/puppet/type/wls_authentication_provider.rb:40:in `block (2 levels) in <module:Puppet>'
==> admin: /tmp/vagrant-puppet/environments/development/modules/easy_type/lib/easy_type/provider.rb:178:in`instances'
==> admin: /tmp/vagrant-puppet/environments/development/modules/orawls/lib/puppet/provider/wls_authentication_provider/prefetching.rb:17:in `prefetch'

**Comment by biemond** [comment]
Ok, can you remove or comment out these values
https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/puppet/hieradata/admin.example.com.yaml#L149-L184

vagrant destroy admin and do up again

plus maybe post your admin yaml file so maybe there is some config error.

**Comment by gemerick** [comment]
Same error. 

[admin.yaml.zip](https://github.com/biemond/biemond-orawls-vagrant-12.2.1/files/99995/admin.yaml.zip)

**Comment by biemond** [comment]
thanks this will help. I will let you know

**Comment by biemond** [comment]
Strange, your config is working fine.

you did destroy the box or re-create it?

it can be some key issue, do you also install the jce policy on the jdk
     cryptography_extension_file => "jce_policy-8.zip",

and can you check with 'netstat -an' if port 7002 and 7001 are alive plus 'ps -ef | grep java'

plus run it in debug mode 
https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/Vagrantfile#L54

**Comment by gemerick** [comment]
I am destroying and recreating each time.

Only port 7101 is open in netstat.

I do have jce in the software folder. I think you are on to something with this. I see errors connecting to node manager:
==> admin: WLSTException: Error occurred while performing nmConnect : Cannot connect to Node Manager. : General SSLEngine problem 

However the jars in are /usr/java/jdk1.8.0_71/jre/lib/security.  I've attached full debug log so perhaps you can spot something. [admin-up.zip](https://github.com/biemond/biemond-orawls-vagrant-12.2.1/files/101921/admin-up.zip)

ps -ef | grep java
oracle    7681  7631  0 15:35 ?        00:00:03 /usr/java/latest/bin/java -server -Xms32m -Xmx200m -Dcoherence.home=/opt/oracle/middleware12c/wlserver/../coherence -Dbea.home=/opt/oracle/middleware12c/wlserver/.. -Dweblogic.ssl.JSSEEnabled=true -Dweblogic.security.SSL.enableJSSE=true -Dweblogic.security.TrustKeyStore=CustomTrust -Dweblogic.security.CustomTrustKeyStoreFileName=/vagrant/truststore.jks -Dweblogic.security.CustomTrustKeystorePassPhrase=welcome -Dweblogic.RootDirectory=/opt/oracle/wlsdomains/domains/Wls1221 -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -Djava.security.policy=/opt/oracle/middleware12c/wlserver/server/lib/weblogic.policy -Dweblogic.nodemanager.JavaHome=/usr/java/latest weblogic.NodeManager -v
oracle    7763  7713  0 15:35 ?        00:00:03 /usr/java/latest/bin/java -server -Xms32m -Xmx200m -Dcoherence.home=/opt/oracle/middleware12c/wlserver/../coherence -Dbea.home=/opt/oracle/middleware12c/wlserver/.. -Dweblogic.ssl.JSSEEnabled=true -Dweblogic.security.SSL.enableJSSE=true -Dweblogic.RootDirectory=/opt/oracle/wlsdomains/domains/plain_Wls -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -Djava.security.policy=/opt/oracle/middleware12c/wlserver/server/lib/weblogic.policy -Dweblogic.nodemanager.JavaHome=/usr/java/latest weblogic.NodeManager -v
oracle    8053  8006  4 15:35 ?        00:00:35 /usr/java/latest/bin/java -server -Xms256m -Xmx512m -Dweblogic.Name=AdminServer -Djava.security.policy=/opt/oracle/middleware12c/wlserver/server/lib/weblogic.policy -Dweblogic.ProductionModeEnabled=true -Dweblogic.system.BootIdentityFile=/opt/oracle/wlsdomains/domains/plain_Wls/servers/AdminServer/security/boot.properties -Dweblogic.nodemanager.ServiceEnabled=true -Dweblogic.nmservice.RotationEnabled=true -XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m -Dweblogic.Stdout=/var/log/weblogic/AdminServer.out -Dweblogic.Stderr=/var/log/weblogic/AdminServer_err.out -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -javaagent:/opt/oracle/middleware12c/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/opt/oracle/middleware12c/wlserver/server -Dweblogic.home=/opt/oracle/middleware12c/wlserver/server weblogic.Server

**Comment by biemond** [comment]
Hi,

So we can see both domains are created and the nodemanagers are running 

5556

```
==> admin: Debug: Sleep[wake up nodemanager](provider=ruby): Running test: /bin/sh -c '/bin/netstat -lnt | /bin/grep ':5556''
==> admin: Debug: Executing: '/bin/sh -c '/bin/netstat -lnt | /bin/grep ':5556'''
==> admin: Debug: Sleep[wake up nodemanager](provider=ruby): The test returned: pid 7699 exit 0 tcp6       0      0 10.10.10.10:5556        :::*                    LISTEN     
==> admin: Debug: Sleep[wake up nodemanager](provider=ruby): Tested is: true
==> admin: Debug: Sleep[wake up nodemanager](provider=ruby): Tested is: true calculated from 1453563033 vs 1453563015
==> admin: Debug: Sleep[wake up nodemanager](provider=ruby): Been running for 3 seconds
==> admin: Debug: Sleep[wake up nodemanager](provider=ruby): Sleeping again
```

And here is the problem

```
==> admin: Info: adminserver action: start with command /opt/oracle/middleware12c/wlserver/common/bin/wlst.sh -skipWLSModuleScanning <<-EOF
==> admin: nmConnect("weblogic","xxxxx","10.10.10.10",5556,"Wls1221","/opt/oracle/wlsdomains/domains/Wls1221","ssl")
==> admin: nmStart("AdminServer")
==> admin: nmDisconnect()
==> admin: EOF and CONFIG_JVM_ARGS=-Dweblogic.ssl.JSSEEnabled=true -Dweblogic.security.SSL.enableJSSE=true -Dweblogic.security.TrustKeyStore=CustomTrust -Dweblogic.security.CustomTrustKeyStoreFileName=/vagrant/truststore.jks -Dweblogic.security.CustomTrustKeystorePassPhrase=welcome
==> admin: Traceback (innermost last):
==> admin:   File "<console>", line 1, in ?
==> admin:   File "<iostream>", line 111, in nmConnect
==> admin:   File "<iostream>", line 553, in raiseWLSTException
==> admin: WLSTException: Error occurred while performing nmConnect : Cannot connect to Node Manager. : General SSLEngine problem 
==> admin: Use dumpStack() to view the full stacktrace :
==> admin: Info: adminserver result: WARNING: This is a deprecated script. Please invoke the wlst.sh script under oracle_common/common/bin.
==> admin: 
==> admin: Initializing WebLogic Scripting Tool (WLST) ...
==> admin: 
==> admin: Welcome to WebLogic Server Administration Scripting Shell
==> admin: 
==> admin: Type help() for help on available commands
==> admin: 
==> admin: wls:/offline> Connecting to Node Manager ...
==> admin: <Jan 23, 2016 4:30:19 PM CET> <Info> <Security> <BEA-090905> <Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true.> 
==> admin: <Jan 23, 2016 4:30:19 PM CET> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true.> 
==> admin: <Jan 23, 2016 4:30:19 PM CET> <Info> <Security> <BEA-090909> <Using the configured custom SSL Hostname Verifier implementation: weblogic.security.utils.SSLWLSHostnameVerifier$NullHostnameVerifier.> 
==> admin: This Exception occurred at Sat Jan 23 16:30:20 CET 2016.
==> admin: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
==> admin: wls:/offline> Not connected to Node Manager
==> admin: wls:/offline> Not connected to Node Manager
==> admin: wls:/offline> 
```

Maybe the nodemanager crashed or there is something wrong with the /vagrant/truststore.jks or its password.
We should check the nodemanager.log for some clues

I will also use this JDK

**Comment by biemond** [comment]
I got the same error with JDK 1.8.72 with 1.8.65 everything was fine.

**Comment by biemond** [comment]
Got it 

_MD5 now disabled for X509 Certificate validating_
MD5 must not be used for digital signatures where collision resistance is required. To prevent the use of X.509 certificates that include an MD5-based digital signature algorithm, MD5 has been added to the jdk.certpath.disabledAlgorithms security property. Applications should upgrade or replace certificates that include an MD5-based digital signature.

Reversing this change is possible by removing MD5 from the jdk.certpath.disabledAlgorithms security property in the java.security file. This is not recommended.

JDK-8141287 (not public)

maybe remove md5 from jre/lib/security/java.security
jdk.tls.disabledAlgorithms=MD5, SSLv3, DSA, RSA keySize < 2048
jdk.tls.disabledAlgorithms=SSLv3, RC4, DH keySize < 768

I will generate new certificates

**Comment by biemond** [comment]
Done, it works with the new certificates

**Comment by gemerick** [comment]
Confirmed here as well. Thank you.

**Comment by adamjk-dev** [comment]
Somewhat confused here, sorry. I hit this issue as well (same error trying to connect to the node manager). Running WL 1221 with an Admin server and node manager, running JDK 1.8.0_45.

When I look at the disabled algorithms, I see:
```
# cat java.security | grep jdk.tls.disabledAlgorithms
#   jdk.tls.disabledAlgorithms=MD5, SSLv3, DSA, RSA keySize < 2048
jdk.tls.disabledAlgorithms=SSLv3
```


---
As an update, we saw this condition on the second puppet run and on (after first install). But, if we reboot, this seems to go away. Perhaps it was related to how we setup TLS and the certs and a reboot was required to bring the admin server / nodemanager up in the proper order or something?
